# Generated by Django 5.0.6 on 2024-07-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'articleinfo'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
