# Generated by Django 5.0.6 on 2024-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='email')),
            ],
        ),
    ]
